### ISSUE TITLE
Categorization Issues

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#176]
Spreadsheet comparing facility types between versions
https://docs.google.com/spreadsheets/d/1GbjXhA1Sr6eDPqxxgorGl_83g_N5Pt4L1JLnzdKziT4/edit?usp=sharing

**Categorization**

facsubgrp City Government Offices changed to Offices, which should it be?
- Why don’t number of factypes within this facsubgrp agree since COLP hasn’t changed

**factype errors**
- [x] No Use-Non Residential Structurese
- [x] High school School – Charter
- [x] Secondary School School – Charter
- [ ] Registered Esl Schools
- [x] Court House and Courthouse
- [x] Wastewater Treatment Plant became Waste Water Treatment Plant

**facsubgrp** 
Child Services and Welfare became two different facsubgrps Child Welfare and Childrens Services

**facgroup** 
Day Care and Pre-Kindergarten became Child Care and Pre-Kindergarten (facsubgrps also changed)
Reasoning for this

**Many new factypes for facsubgrp Non-Public K-12 Schools**
- [ ]
- Sewer Districts
- Jails
- School Library Systems
- Presbytarian Organizations Providing Services

**facsubgrp** Public K-12 Schools
**facgroup** Health Care – all different
**factype** Public Libraries became Public Library

**Comment by baolingz** [comment]
Reassigin factype for `dot_ferryterminals`
```
SET factype = (CASE WHEN UPPER(name) LIKE '%TERMINAL%' THEN 'Ferry Terminal'
		    WHEN UPPER(name) LIKE '%LANDING%' THEN 'Ferry Landing'
	     END),
```

**Comment by baolingz** [comment]
@AmandaDoyle Here are the factypes we mentioned in today's standup. Changing classification are in blue, problemetic `facsubgrp` are in green.
<img width="1677" alt="Screen Shot 2019-07-31 at 4 26 07 PM" src="https://user-images.githubusercontent.com/31453240/62245746-4123ec00-b3b0-11e9-968e-8e4780115c9f.png">

**Comment by baolingz** [comment]
The issue related to `factype` falling under `Public and Private Special Education Schools` is solved.
