### ISSUE TITLE
Fix facilities that don't have names (DOT to start)

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/db-facilities#196]

**Comment by AmandaDoyle** [comment]
@hannahkates how do you propose fixing these?

**Comment by hannahkates** [comment]
@AmandaDoyle I had already fixed this. It was just an issue for Manned Facilities (filling in another label in the data) and Parking lots (filling in with "Parking Lot").

https://github.com/NYCPlanning/db-facilities/blob/simple/2_assembly/insert/dot_facilities_mannedfacilities.sql#L54

https://github.com/NYCPlanning/db-facilities/blob/simple/2_assembly/insert/dot_facilities_parkingfacilities.sql#L54
