### ISSUE TITLE
Develop QAQC report(s):

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#219]
In addition to current reports also output the following summary statistics to help in QAQC procedures: 

- [ ] number of records from each source in current and previous version (with this previous version, parse the pgtable column by `;` so if you have `dcas_colp; acs_daycare` you'll have +1 for dcas_colp and +1 for acs_daycare
- [ ] change in number of facility type / groupings in current and previous version
- [ ] number of unmapped records by source
- [ ] number of unmapped records by facility type / groupings

**Comment by SPTKL** [comment]
```
SELECT datasource, datasource_old, count_old, count_new, count_new - count_old as diff 
from(
	SELECT REPLACE(datasource, 'facilities_', '' ) as datasource_join, datasource as datasource_old, count(datasource) as count_old from (
		SELECT unnest(string_to_array(pgtable, ';')) as datasource 
		from facilities_20190110) as a group by datasource) a
FULL JOIN
(select datasource, count(datasource) as count_new from facilities group by datasource) b 
on a.datasource_join = b.datasource;
```
[count_by_source_comparison.xlsx](https://github.com/NYCPlanning/db-facilities-tmp/files/3574757/count_by_source_comparison.xlsx)
