### ISSUE TITLE
Facility types with one records

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#220]
Review Facility types / grouping with one record and see if that facility can be classified into a different facility type, or if that facility type exists in a different subgroup see if the facility type can be assigned to another subgroup

**Comment by baolingz** [comment]
```
select facdomain, facgroup, facsubgrp, factype, datasource, coalesce(count(*),0) as count_new
from facilities
group by facdomain, facgroup, facsubgrp, factype, datasource
having coalesce(count(*),0) = 1;
```
https://docs.google.com/spreadsheets/d/13a86imc98GxfDjV5XC7Scqz6hZRhnuFDo7bXTQXRTHs/edit#gid=553496973

**Comment by AmandaDoyle** [comment]
@baolingz can you give me access to the spreadsheet, or provide a link with read or write access?

**Comment by baolingz** [comment]
@AmandaDoyle I just updated the link ^
