### ISSUE TITLE
Change capacity type value

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#243]
DOE: Seats overseen by DOE
ACS: Seats in ACS contract
DOHMH - assigned using the Program Type field:
Infant and toddler maxiumum capacity calculated by DOHMH
Preschooler maxiumum capacity calculated by DOHMH

**Comment by hannahkates** [comment]
ACS looks good.
DOHMH capacitytype looks good, but the capacity value is stored in array brackets.
Can't evaluate DOE UPK, because those records did not get inserted into the facilities table.
