### ISSUE TITLE
2020 March Update - QAQC: heroku app improvements

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities#296]
- full panel qaqc script refactor to simplify
- complete table new
- incorporate new important factypes

**Comment by AmandaDoyle** [comment]
Adding to the above:

- [ ] Add the following to important factypes 
- Libraries
- Emergency medical stations
- Hospitals
- Nursing homes
- Adult care
- Senior centers

**Comment by AmandaDoyle** [comment]
Notes: will clean up tomorrow
Update Change in Number of Records by datasource graph to only include one datasource
Add text ot charts
change in percent of records should not include records where 100% are geocoded or didn't change
Make factype values visible in table
NYCHA
Might not want to show NYCHA community center details and may not want to not include day care if it's a duplicate, may need to change facsubgroup mapping for NYCHA

**Comment by SPTKL** [comment]
+ everything is implemented
+ It's not possible change legend order (it's automatically generated, I have no control over)
+` Change in number of records by factype` is removed because there are too many factypes, a table is a better option for review
