### ISSUE TITLE
20Q4 Update -- Master Issue (old template)

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#309]
# Data Loading

- [ ]  *acs_daycareheadstart*
    + status: 
    + comments: discontinued, we are no longer using this data source
- [ ]  bpl_libraries
    + status:
- [x]  dca_operatingbusinesses
    + status:
- [ ]  dcas_colp
    + status:
    + comments: no new version of COLP released yet (using 2018 November version on Bytes)
- [x]  dcla_culturalinstitutions
    + status: Data Last UpdatedApril 17, 2019
- [ ]  dcp_pops
    + status:
    + comments: downloaded from the POPS app
- [x]  dep_wwtc
    + status:
    + comments: this dataset doesn't need updates
- [x]  dfta_contracts
    + status:
- [x]  doe_busroutesgarages
    + status:
- [ ]  doe_lcgms
    + status:
    + comments: this dataset is updated for CEQR
- [ ]  sca_enrollment_capacity
    + status:
- [x]  doe_universalprek
    + status:
- [x]  dohmh_daycare
    + status:
- [ ]  *__dot_bridgehouses__*
    + status: 
    + comments: might need refresh from FTP
- [ ]  *__dot_ferryterminals__*
    + status: 
    + comments: might need refresh from FTP
- [ ]  *__dot_mannedfacilities__*
    + status: 
    + comments: might need refresh from FTP
- [ ]  *__dot_pedplazas__*
    + status: 
    + comments: might need refresh from FTP
- [ ]  *__dot_publicparking__*
    + status: 
    + comments: might need refresh from FTP
- [x]  dpr_parksproperties
    + status:
- [ ]  *__dsny_mtsgaragemaintenance__*
    + status:
    + comments: might need refresh from FTP
- [ ]  dycd_afterschoolprograms
    + status: Data Last UpdatedSeptember 16, 2017 on open data
https://data.cityofnewyork.us/Education/DYCD-after-school-programs/mbd7-jfnc
- [X]  fbop_corrections
    + status: 
    + comments: doesn't need update, no new facilities added
- [ ]  fdny_firehouses
    + status: updated
- [ ]  *__foodbankny_foodbanks__*
    + status: NA
    + comments: need to scrape data from google map and the downloaded KML does not have spatial info
- [ ]  hhc_hospitals
    + status:
- [ ]  __hra_centers__
    + status:
    + comments: new data source https://data.cityofnewyork.us/City-Government/Community-Health-Centers/b2sp-asbg/data
- [ ]  *__moeo_socialservicesiteloactions__*
    + status:
    + comments: receive by email
- [ ]  nycdoc_corrections
    + status:
    + comments: no update needed, hand checked no new facilities added
- [X]  nycha_communitycenters
    + status:
- [X]  nycha_policeservice
    + status:
- [ ]  nycourts_courts
    + status:
    + comments: hand check
- [ ]  nypl_libraries
    + status:
    + comments: not sure there are new libraries added, but the scraper worked
- [ ]  nysdec_lands
    + status:
    + comments: for some reason gdal won't read the link, so I had to manual update. not sure if new records added tho
- [X]  nysdec_solidwaste
    + status:
- [X]  nysdoccs_corrections
    + status:
    + comments: 1 facility in queens, 1 facility in Manhattan, 0 in the other 3 boros. 
- [X]  nysdoh_healthfacilities
    + status:
- [ ]  nysdoh_nursinghomes
    + status:
- [ ]  nysed_activeinstitutions
    + status:
    + comments: manually downloaded selected table __  All Institutions: Active Institutions with GIS coordinates and OITS Accuracy Code - Select by County__ CSV from [website](https://eservices.nysed.gov/sedreports/list?id=1) and loaded into S3
- [ ]  __nysed_nonpublicenrollment__
    + status:
    + comments: this data set was not previously included in the list for some reason. 
- [ ]  nysoasas_programs
    + status:
    + comments: original link no longer work, switch to https://edm-recipes.nyc3.digitaloceanspaces.com/2020-03-23/Treatment_Providers_OASAS_Directory_Search_23-Mar-20.csv
- [ ]  nysomh_mentalhealth
    + status:
- [ ]  nysopwdd_providers
    + status:
- [ ]  nysparks_historicplaces
    + status:
- [ ]  nysparks_parks
    + status:
- [ ]  qpl_libraries
    + status:
- [ ]  sbs_workforce1
    + status:
- [ ]  uscourts_courts
    + status:
    + comments: scraper ran smoothly, not sure there are new facilities added
- [ ]  usdot_airports
    + status:
    + comments: on argis site, it says updated 2020/02/17, no url change
- [ ]  usdot_ports
    + status:
    + comments: url changed to https://data-usdot.opendata.arcgis.com/datasets/major-ports-1, data is as of __2019/12/17__
- [ ]  usnps_parks
    + status:
    + comments: manually downloaded from url and loaded into s3

**Comment by mgraber** [comment]
See #311 for update tracker using new template
