### ISSUE TITLE
20Q4 UPDATE

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-facilities#311]
# Data Loading

## Needs further exploration/instruction
@AmandaDoyle 
- [x]  ~dcas_colp~ dcp_colp
    + Source: Bytes
    + Source update date (latest Bytes publish date):
    + Our lastest download date: 2020/11/24
    + **Need to adjust code in response to new schema** #313 
- [ ]  *__dsny_mtsgaragemaintenance__*
    + Source: FTP
    + Source update date:
    + Our lastest download date:  2019/11/15
- [ ]  __hra_centers__
    + Source: OpenData (?)
    + OpenData table name/url: **No longer exists as a single table**
    + Source update date (as listed on OpenData):
    + Our lastest download date: 2020/03/24
- [ ]  *__moeo_socialservicesiteloactions__*
    + Source: Local file, recieved via email from (?)
    + Our lastest download date: 2019/11/12

## To-do
- [x]  uscourts_courts
    + Source: 
    + Source url: http://www.uscourts.gov/court-locator/city/New%20York/state/NY
    + Source update date:
    + Our lastest download date: 2020/07/08
    + **Scraper in recipe repo needs bs4 dependency**
> update: `uscourts_courts` is loaded using repo dispatch

- [x]  nysdec_lands
    + Source: DEC Website
    + Source url: http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1114
    + Our latest download date: 2020/03/23
    + **Downloaded zip isn't readable through recipe app**
> update: problem resolved after switching to [rest service](https://gisservices.its.ny.gov/arcgis/rest/services/dec_lands/MapServer/0/query?where=1=1&outfields=*&f=geojson)
- [x]  doe_lcgms
    + Source: Download from website
    + Our lastest download date: 2020/07/08
    + **File can only open in excel -- converted to csv from excel**
- [ ]  dcp_pops
    + Source: downloaded from the POPS app
    + Our lastest download date:  2020/07/10
    + **Do this last**

## Complete
- [x]  *acs_daycareheadstart*
    + **Discontinued, we are no longer using this data source**
- [x]  bpl_libraries
    + Source: Scraped from BPL website
    + OpenData table name/url: https://www.bklynlibrary.org/locations/json
    + Our lastest download date: 2020/03/23
- [x]  dca_operatingbusinesses
    + Source: OpenData
    + Source table name/url: https://data.cityofnewyork.us/Business/Legally-Operating-Businesses/w7w3-xahh
    + Our lastest download date: 2020/03/23
- [x]  dcla_culturalinstitutions
    + Source: OpenData
    + Source table name/url: https://data.cityofnewyork.us/Recreation/DCLA-Cultural-Organizations/u35m-9t32
    + Our lastest download date:  2020/07/06
- [x]  dep_wwtc
    + Source: GitHub
    + Source update date (latest upload to GitHub):
    + Our latest download date: 2020/01/05
    + **This dataset doesn't need updates**
- [x]  dfta_contracts
    + Source: OpenData
    + OpenData table name/url: https://data.cityofnewyork.us/Social-Services/DFTA-Contracts/6j6t-3ixh
    + Our lastest download date: 2020/10/23
- [x]  doe_busroutesgarages
    + Source: OpenData
    + OpenData table name/url: https://data.cityofnewyork.us/Transportation/Routes/8yac-vygm
    + Our lastest download date: 2020/10/01
- [x]  sca_enrollment_capacity
    + Source: OpenData
    + OpenData table name/url: https://data.cityofnewyork.us/Education/Enrollment-Capacity-And-Utilization-Reports-Target/8b9a-pywy
    + Source update date (as listed on OpenData): 2019/12/30
    + Our lastest download date: 2019/12/30
- [x]  doe_universalprek
    + Our lastest download date: 2020/07/07
- [x]  dohmh_daycare
    + Source: OpenData
    + OpenData table name/url: https://data.cityofnewyork.us/Health/DOHMH-Childcare-Center-Inspections/dsg6-ifza
    + Our lastest download date: 2020/10/27
- [x]  *__dot_bridgehouses__*
    + Source: email
    + Our lastest download date: 2019/11/15
- [x]  *__dot_ferryterminals__*
    + Source: email
    + Our lastest download date: 2019/11/15
- [x]  *__dot_mannedfacilities__*
    + Source: email
    + Our lastest download date: 2019/11/15
- [x]  *__dot_pedplazas__*
    + Source: email
    + Our lastest download date: 2019/11/15
- [x]  *__dot_publicparking__*
    + Source: email
    + Our lastest download date: 2019/11/15
- [x]  dpr_parksproperties
    + Source: OpenData
    + OpenData table name/url: https://nycopendata.socrata.com/Recreation/Parks-Properties/enfh-gkve
    + Source update date (as listed on OpenData):  2020/10/20
    + Our lastest download date:  2020/10/27
- [x]  dycd_afterschoolprograms
    + Source: OpenData
    + OpenData table name/url: https://data.cityofnewyork.us/Education/DYCD-after-school-programs/mbd7-jfnc
    + Source update date (as listed on OpenData):  2017/09/16
    + Our lastest download date: 2020/03/23
- [x]  fbop_corrections
    + Source: Bureau of Prisons
    + Source url: https://www.bop.gov/locations/list.jsp
    + Our lastest download date: 2020/01/05
    + **Probably doesn't need update, no new facilities added**
- [x]  fdny_firehouses
    + Source: OpenData
    + OpenData table name/url: https://data.cityofnewyork.us/Public-Safety/FDNY-Firehouse-Listing/hc8x-tcnd
    + Source update date (as listed on OpenData): 2017/09/16
    + Our lastest download date: 2020/03/23
- [x]  *__foodbankny_foodbanks__*
    + Source: Foodbank NYC 
    + Source url: http://www.foodbanknyc.org/get-help/
    + Source update date: 2020/11/12
    + Our lastest download date: 2020/11/13
> **Need to scrape data from google map and the downloaded KML does not have spatial info**
> use https://mygeodata.cloud/converter/kmz-to-csv to convert kmz to csv, then use recipe app to load in the csv
- [x]  hhc_hospitals
    + Source: OpenData
    + OpenData table name/url: https://data.cityofnewyork.us/Health/Health-and-Hospitals-Corporation-HHC-Facilities/f7b6-v6v3
    + Source update date (as listed on OpenData): 2017/09/08
    + Our lastest download date: 2020/03/2
- [x]  nycdoc_corrections
    + Source: NYCDOC locations directory
    + Source url: https://www1.nyc.gov/site/doc/about/facilities-locations.page
    + Our lastest download date:  2019/12/10
- [x]  nycha_communitycenters
    + Source: OpenData
    + OpenData table name/url: https://data.cityofnewyork.us/Social-Services/Directory-of-NYCHA-Community-Facilities/crns-fw6u
    + Source update date (as listed on OpenData):
    + Our lastest download date: 2020/10/27
- [x]  nycha_policeservice
    + Source: OpenData
    + OpenData table name/url: https://data.cityofnewyork.us/Housing-Development/NYCHA-PSA-Police-Service-Areas-/72wx-vdjr
    + Source update date (as listed on OpenData):
    + Our lastest download date: 2020/10/27
- [x]  nycourts_courts
    + Source: GitHub (?)
    + Source url: http://www.nycourts.gov/courts/nyc/criminal/generalinfo.shtml#BRONX_COUNTY
    + **Hand-check for new locations**
    + Our latest download date: 2020/03/23
- [x]  nypl_libraries
    + Source: Scrape from NYPL website
    + Source url: https://www.nypl.org/locations/list
    + Our latest download date: 2020/03/23
- [x]  nysdec_solidwaste
    + Source: OpenData
    + OpenData table name/url: https://data.ny.gov/Energy-Environment/Solid-Waste-Management-Facilities/2fni-raj8
    + Our lastest download date: 2020/10/27
- [x]  nysdoccs_corrections
    + Source: DOCCS NY
    + Source url: http://www.doccs.ny.gov/faclist.html
    + Hand check for 1 facility in queens, 1 facility in Manhattan, 0 in the other 3 boros 
- [x]  nysdoh_healthfacilities
    + Source: OpenData
    + OpenData table name/url: https://health.data.ny.gov/Health/Health-Facility-General-Information/vn5v-hh5r
    + Our lastest download date: 2020/10/27
- [x]  nysdoh_nursinghomes
    + Source: OpenData
    + OpenData table name/url: https://health.data.ny.gov/Health/Nursing-Home-Weekly-Bed-Census-Last-Submission/izta-vnpq
    + Our lastest download date: 2020/10/27
- [x]  nysed_activeinstitutions
    + Source: DOCCS NY
    + Source url: All Institutions: Active Institutions with GIS coordinates and OITS Accuracy Code - Select by County__ CSV from [website](https://eservices.nysed.gov/sedreports/list?id=1)
    + Our lastest download date: 2020/07/08
- [x]  __nysed_nonpublicenrollment__
    + Source: 
    + Source url: 
    + Our lastest download date: 2020/07/08
- [x]  nysoasas_programs
    + Source: 
    + Source url: https://webapps.oasas.ny.gov/providerDirectory/index.cfm?search_type=2
    + Source update date: 2020/11/13
    + Our lastest download date: 2020/11/13
> the url is always in the form e.g. `https://webapps.oasas.ny.gov/providerDirectory/download/Treatment_Providers_OASAS_Directory_Search_13-Nov-20.csv`
- [x]  nysomh_mentalhealth
    + Source: OpenData
    + Source url: https://data.ny.gov/Human-Services/Local-Mental-Health-Programs/6nvr-tbv8
    + Source update date: 2018/09/10
    + Our lastest download date: 2020/03/23
- [x]  nysopwdd_providers
    + Source: OpenData
    + OpenData table name/url: https://data.ny.gov/Human-Services/Directory-of-Developmental-Disabilities-Service-Pr/ieqx-cqyk
    + Source update date (as listed on OpenData): 2020/02/18
    + Our lastest download date: 2020/03/23
- [x]  nysparks_historicplaces
    + Source: OpenData
    + OpenData table name/url: https://data.ny.gov/Recreation/National-Register-of-Historic-Places/iisn-hnyv
    + Source update date (as listed on OpenData): 2019/12/18
    + Our lastest download date: 2020/03/23
- [x]  nysparks_parks
    + Source: OpenData
    + OpenData table name/url: https://data.ny.gov/Recreation/State-Park-Facility-Points/9uuk-x7vh
    + Source update date (as listed on OpenData): 2019/12/30
    + Our lastest download date: 2020/03/23
- [x]  qpl_libraries
    + Source: OpenData
    + OpenData table name/url: https://data.cityofnewyork.us/Education/Queens-Library-Branches/kh3d-xhq7
    + Source update date (as listed on OpenData): 2018/06/20
    + Our lastest download date: 2020/03/23
- [x]  sbs_workforce1
    + Source: OpenData
    + OpenData table name/url: https://data.cityofnewyork.us/dataset/Center-Service-Locations/6smc-7mk6
    + Source update date (as listed on OpenData): 2017/04/26
    + Our lastest download date: 2020/03/23
- [X]  usdot_airports
    + Source: OpenData
    + OpenData table name/url: https://hub.arcgis.com/datasets/usdot::airports
    + Source update date (as listed on OpenData): 2020/08/10
    + Our lastest download date: 2020/03/23

- [X]  usdot_ports
    + Source: OpenData
    + OpenData table name/url: https://hub.arcgis.com/datasets/usdot::ports
    + Source update date (as listed on OpenData): 2020/01/16
    + Our lastest download date: 2020/03/23

- [x]  usnps_parks
    + Source: USNPS website
    + Source url: https://irma.nps.gov/DataStore/Reference/Profile/2225713
    + Source update date: 2020/09/30
    + Our lastest download date: 2020/07/07

**Comment by SPTKL** [comment]
switching nysdec_lands to esri rest service instead of file download
https://gisservices.its.ny.gov/arcgis/rest/services/dec_lands/MapServer/0/query?where=1=1&outfields=*&f=geojson

**Comment by SPTKL** [comment]
released
