### ISSUE TITLE
Adjust COLP filtering

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-facilities#313]
I am trying to translate the old filtering of COLP into the new schema and parcel cleaning. This is what we use to do:
```sql
SELECT *
	FROM dcas_colp
	WHERE colp_type ~* 'maintenance|storage|Infrastructure|Office|residential|no use|private' 
		 OR usedec ~* 'Office Leased By Educ|Emergency|Safety|Police|security|courthouse|ambulance station|OTHER SECURE DETENTION FACILITY'
		 OR name ~* 'DETENTION FACILITY'
		 OR (usedec ~* 'JAIL' AND (name LIKE '%COURT%' OR name LIKE '% CT %'));
```
I believe `colp_type` is now most similar to `"EXCATDESC"` , `usedec` is now `"USETYPE"`, and `name` is now `"PARCELNAME"`. A potential new filter is:

```sql
SELECT *
FROM colp 
WHERE "EXCATDESC" ~* 'maintenance|storage|infrastructure|office|residential|no use|private' 
		 OR "USETYPE" ~* 'office leased by educ|emergency|safety|police|security|courthouse|ambulance station|other secure detention facility'
		 OR "PARCELNAME" ~* 'detention facility'
		 OR ("USETYPE" ~* 'jail' AND ("PARCELNAME" LIKE '%COURT%' OR "PARCELNAME" LIKE '% CT %'));
```

With those changes, some of the filters don't return anything. 
The ones that don't return anything are `"USETYPE" ~* 'security'`, `"PARCELNAME" ~* 'detention facility'`, and `"USETYPE" ~* 'jail' AND ("PARCELNAME" LIKE '% CT %')`. The last is probably a result of our parcel name cleaning.

Should these filters still be included?

**Comment by AmandaDoyle** [comment]
I don't know if this is cleaner, but this gets you the right subset

`SELECT *
FROM colp WHERE CONCAT("CATEGORY","EXPANDCAT") IN
('11', '12', '14', '16', '17', '28','29','38')
AND "USECODE" NOT IN
('0800','0870','0900','0939','1000','1100','1139','1200','1229','1300','1350','1400','0500','0520')
AND "USECODE" NOT LIKE '02%'
OR "USECODE" = '0230';`

**Comment by mgraber** [comment]
@AmandaDoyle 
The current workflow changes capitalization using `initcap(parcelname)`. This results in strange capitalization for abbreviations, such as `Nypd`,`Cuny`,`Nys`, and `Ps`.

Would it be better to instead change the standard to capitalization for all sources? It is easier to make a change in that direction.
