### ISSUE TITLE
20Q4 - Second Round improvement

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities#339]
# Issues:
- [ ] `dcp_colp`
We have noticeable records decline from 4100 -> 1600
 
# Investigate:
- [ ] `nysdoccs_corrections` lost 1 facility, but we didn't even change the input data?
- [x] `uscourts_courts` lost 1 facility, ~but we didn't even change the input data~?
> The table `uscourts_courts."2020/03/23"` has locationid 1708 but the table `uscourts_courts."2020/11/19"` does not.

**Comment by AmandaDoyle** [comment]
FacDB feedback from Lynn for AD to investigate
- [ ] 1520 - keep use code out
- [ ] COLP use police stations (central park, fresh kills landfill)

- [ ] Geocoding rejects
- where does each field come from?
- look into records that were geocoded without zip code or borough
- GRC of 0
- GRC of 11 --> what happened with these
- 72 orange street
- lots of schools

- [ ] NYCHA factypes - a lot changed and with groupings

**Comment by SPTKL** [comment]
@AmandaDoyle  GRC of 0 means success, we don't need to look into those?
