### ISSUE TITLE
COLP exclusions and geocoding errors

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-facilities#345]
1. BBL 5011090014 and 5011090018 – COLP has records with usetype ASPHALT PLANT, agency DOT on both these lots. Only the first is in FacDB.
> I see both of these included in facilities."2020/12/18". One has `facname = 'ASPHALT PLANT' and uid = '9954f947ece8e5fd7dbe2b0f3c332ea8'` and the other has `facname = 'VILLA MARIN' and uid = 'add2e7f2c8d01915e11adba6710c970b'`. Both of these records have `overabbrev = 'NYCDOT'` and `factype = 'ASPHALT PLANT'`.

My mistake - the asphalt plant that was dropped is BBL 4017910068 at 30-01 HARPER ST, SI.

2. BBL 3003120024 – COLP has two records with agency CB306, one with usetype OFFICE and one with AGENCY OFFICE. FacDB has only the first. Does the dedup process drop AGENCY OFFICE?
> This deduplication happens because we identify records where `usetype LIKE '%OFFICE%'`, then take the subset `SELECT DISTINCT ON (parcelname, point_location, agency)`

3. COLP records with BBL 1005330001, agency CB102. Address is 3 Washington Square, which geocodes with a warning to Washington Square Park. In FacDB, the BBL is changed to match the park (1005490001), which is wrong. The point is in the right place, so it must uses the x,y coordinates from COLP. Need to review warnings from Geosupport. <-- we might need to update how we Geocode COLP but before we change anything we need to check for any impacts

> The portion of the colp script that determines both bbl and geometry is here:
https://github.com/NYCPlanning/db-facilities/blob/f2ee736e235e1dcc1e64b0448e7bb208e603a32e/facdb_build/sql/dcp_colp.sql#L43-L50
> We could add in logic to line 48 to include cases with a particular warning. That way we use the source value, `bbl`, and not the Geosupport-corrected value `geo_bbl`

**Comment by SPTKL** [comment]
we are not geocoding colp, closing this
