### ISSUE TITLE
Incorporate new MOEO data

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#349]
Incorporate latest MOE data, which was emailed by Martha, but it scheduled to go on Open Data.  Pull from Open Data if it's available.  Schema is significantly different so the workflow of bringing in the MOE data will need to be refactored.

**Comment by AmandaDoyle** [comment]
MOEO tables on Open Data
[Verified Locations for NYC City-Funded Social Service Contracts - Sites](https://data.cityofnewyork.us/City-Government/Verified-Locations-for-NYC-City-Funded-Social-Serv/y9si-s7ab)
[Verified Locations for NYC City-Funded Social Service Contracts - Contracts](https://data.cityofnewyork.us/City-Government/Verified-Locations-for-NYC-City-Funded-Social-Serv/2bvn-ky2h)
[Verified Locations for NYC City-Funded Social Service Contracts - Providers
](https://data.cityofnewyork.us/City-Government/Verified-Locations-for-NYC-City-Funded-Social-Serv/x882-mwt5)
[Verified Locations for NYC City-Funded Social Service Contracts - Programs
](https://data.cityofnewyork.us/City-Government/Verified-Locations-for-NYC-City-Funded-Social-Serv/3t6s-yb67)

New tables need to be mapped to FacDB schema.  
Additionally, we can use these new datasets to test out any new geocoding workflows.

**Comment by mgraber** [comment]
## Field mapping for moeo_socialservicesitelocations:

Existing name | Input name | Table 
-- | -- | --
organization_id | |
service_id | |
location_id | |
address_id | |
service_location_id | site_id (?) | Site
agency_id | |
contract_id | contract_id | Site
verify_id | |
file_source | |
agency_name | agency_name | Site
ages_served | |
contract_number | contract_number | Contracts
contract_amount | amount | Contracts
contract_start | start_date | Contracts
contract_end | end_date | Contracts
fiscal_year | fiscal_year | Contracts
provider_name | provider_name | Providers
ein | provider_ein | Providers
program_name | |
source_agency_id | |
bbl | bbl | Site
bin | bin | Site
cd | community_board | Site
council | council_district | Site
latitude | latitude | Site
longitude | longitude | Site
nta | nta | Site
tract | census_tract | Site
site_catchment | catchment_type (or catchment_zone?) | Site
site_address_1 | address_1 | Site
site_address_2 | address_2 | Site
site_boro | borough | Site
site_budget | site_budget | Site
site_city | city | Site
site_name | site-name | Site
site_phone | |
alternate_site_phone | |
site_state | state | Site
site_country | |
site_url | |
site_zip | postcode | Site
verification_date | |
active | |
status | |
notes | notes | Site
site_intersection_street_1 | |
site_intersection_street_2 | |
street_number | |
street_name | |
suppress_address | |
schedule | |
grades_served | |
population_served | |

**Comment by mgraber** [comment]
https://github.com/NYCPlanning/db-data-library/pull/160
