### ISSUE TITLE
Refine NYCHA subgroup classifications

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#350]
Right now everything is classified as a community center and that's probably not right.
The current logic is [here](https://github.com/NYCPlanning/db-facilities/blob/main/facdb_build/sql/nycha_communitycenters.sql#L48).  
Subset of data as it appears in FacDB can be selected with the following query `SELECT * FROM facilities WHERE datasource = 'nycha_communitycenters';`
Looking at the `program_type` some of these facilities are better classified as another subgroup.  Before implementing anything we need to make a proposal of how to change the classification

**Comment by mgraber** [comment]
Distinct `program_type`:

Adult Social Day Care
ATTAIN LAB
Case Management - Seniors
Case Management /Child Welfare Program
Case Management/ Referral Services
Child Care
Child Care  *
Child Care - Early Intervention (ABA)
Child Care - UPK 2014
Child Care - UPK 2015
Child Care - UPK 2016
Child Care /Community Center
Child Care /Community Center/Credit Union
Citibike Bike Storage
Community Center
Community Center - Cornerstone
Community Center - Developmental Disabilities
Community Center / Sports
Community Center/ Health Clinic
Computer Lab
Domestic Violence Program/Counseling
Education / IHAD Literacy
Education /Literacy Center
ESL Classes
Family Partnerships
Family Services
Family/Youth Program / Meals on Wheels Offices
Food Pantry
Head Start
Head Start / Jobs Plus / Community Center
Health Clinic
Health Clinic (mental)
Health Clinic *
Heating & CCTV
Job Readiness
Jobs Plus
Library
Manhattan CCTV Unit
NGO Staff
NORC
NORC/ Child Care / Community Center / Health Clinic
NYCHA - ORRR
NYPD
Office Space, Training, RA Use
Plasterer's Shop
RESERVED - OPERATIONS
School
Senior Center
Senior Services/Caregiver support
Sports - Boxing Program
Storage
STV Contractor
SYEP 2019 (see notes)
TA USE
TA USE - lighting vendor
TA USE / NYCHA storage
Unknown
Urban Family Center
Urban Family Center - Shelters
Vacant
Vocational/Trade School
Youth Programs

**Comment by mgraber** [comment]
@AmandaDoyle What is the distinction between job-related programs that in 'Workforce Development' and those in 'YOUTH CENTERS, LITERACY PROGRAMS, AND JOB TRAINING SERVICES'?
