### ISSUE TITLE
2021 Geocoding Refactor

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities#355]
## Scenario 1 Good address :
1. 1B
2. Get BIN
3. Get BIN centroid from DOITT
4. If not then BBL

## Scenario 2: If Good BBL
Whenever a BBL is given, we trust the given BBL. 
Then use BBL to geocode and get XY. 
1. If there's only 1 BIN in the lot, we might assign the BIN
2. No address

## Scenario 3: Geosupport failure but have XY
1. Dedup XY -> maybe not even used for dedup
2. Output Bare XY ? Needs more case by case discussion
3. Back fill BBL, BIN, ZIPCODE, BORO

## Output for GRU
- factypes that should have a building
- bad streetnames
- All errors and warnings 
- intersection
- colp is exception, we will take what's already given
- We should never assign Addresses based on BBL and BIN
- 41, 42, anything that doesn't get a bin, million bin/dummy bin
- Look like buildings but no buildings on the lot
- #360 When outputting QAQC tables, specify 1a 1e for the return codes when getting rejects from 1b

**Comment by SPTKL** [comment]
#360 When outputting QAQC tables, specify 1a 1e for the return codes when getting rejects from 1b

**Comment by SPTKL** [comment]
we should create a facdb_geo table to keep track of spatial information, primarily composed of `uid`, `geom`, and `geomsource` (if necessary)
```sql
select 
    uid, 
    wkb_geometry,
    st_point(
    	nullif(geo_1b->'result'->>'geo_latitude','')::double precision,
    	nullif(geo_1b->'result'->>'geo_longitude','')::double precision
    ) as geom_1b,
    st_point(
    	nullif(geo_bl->'result'->>'geo_latitude','')::double precision,
    	nullif(geo_bl->'result'->>'geo_longitude','')::double precision
    ) as geom_bl,
    st_point(
	    nullif(geo_bn->'result'->>'geo_latitude','')::double precision,
	    nullif(geo_bn->'result'->>'geo_longitude','')::double precision
	) as geom_bn
from facdb_base
```

then `facdb_geo` will be used to assign `geom`, `lat/lon`, `x/y`, and other spatial boundaries

**Comment by SPTKL** [comment]
extract info from 1b
```sql
select 
	uid,
	geo_1b->'inputs'->>'input_hnum' as input_hnum,
	geo_1b->'inputs'->>'input_sname' as input_sname,
	geo_1b->'inputs'->>'input_borough' as input_borough,
	geo_1b->'inputs'->>'input_zipcode' as input_zipcode,
	nullif(geo_1b->'result'->>'geo_house_number','') as geo_house_number,
	nullif(geo_1b->'result'->>'geo_street_name','') as geo_street_name,
	nullif(geo_1b->'result'->>'geo_borough_code','') as geo_borough_code,
	nullif(geo_1b->'result'->>'geo_zip_code','') as geo_zip_code,
	nullif(geo_1b->'result'->>'geo_bin','') as geo_bin,
	nullif(geo_1b->'result'->>'geo_bbl','') as geo_bbl,
	nullif(geo_1b->'result'->>'geo_city','') as geo_city,
	nullif(geo_1b->'result'->>'geo_commboard','') as geo_commboard,
	nullif(geo_1b->'result'->>'geo_nta','') as geo_nta,
	nullif(geo_1b->'result'->>'geo_council','') as geo_council,
	nullif(geo_1b->'result'->>'geo_censtract','000000') as geo_censtract,
	nullif(geo_1b->'result'->>'geo_policeprct','') as geo_policeprct,
	nullif(geo_1b->'result'->>'geo_schooldist','') as geo_schooldist,
	nullif(geo_1b->'result'->>'geo_grc','') as geo_grc,
	nullif(geo_1b->'result'->>'geo_grc2','') as geo_grc2,
	nullif(geo_1b->'result'->>'geo_reason_code','') as geo_reason_code,
	nullif(geo_1b->'result'->>'geo_message','') as geo_message
from facdb_base
```

**Comment by SPTKL** [comment]
code for selecting geometry based on a hierarchy 
```sql
SELECT 
	uid,
	coalesce(geom_bldg, 
		coalesce(geom_bn, 
			coalesce(geom_pluto, 
				coalesce(geom_bl, 
					coalesce(geom_1b, 
						wkb_geometry))))) as geom,
	coalesce(source_bldg, 
		coalesce(source_bn, 
			coalesce(source_pluto, 
				coalesce(source_bl, 
					coalesce(source_1b, 
						source_wkb))))) as geomsource
FROM (
SELECT 
	a.*, 
	b.wkb_geometry as geom_bldg,
	(case when a.wkb_geometry is not null then 'wkb_geometry' end) as source_wkb,
	(case when geom_1b is not null then '1b' end) as source_1b,
	(case when geom_bl is not null then 'bl' end) as source_bl,
	(case when geom_bn is not null then 'bn' end) as source_bn,
	(case when geom_pluto is not null then 'pluto bbl centroid' end) as source_pluto,
	(case when b.wkb_geometry is not null then 'building centroid' end) as source_bldg
FROM (
	SELECT
		a.*,
		st_centroid(b.wkb_geometry) as geom_pluto
	FROM (
		SELECT 
		    uid, 
		    wkb_geometry,
		    geo_1b->'result'->>'geo_bbl' as geo_bbl, 
		    (CASE WHEN geo_1b->'result'->>'geo_bin' IN ('5000000', '4000000', '3000000', '2000000', '1000000') 
		    	THEN NULL ELSE geo_1b->'result'->>'geo_bin' END) as geo_bin, 
		    st_point(
		    	nullif(geo_1b->'result'->>'geo_latitude','')::double precision,
		    	nullif(geo_1b->'result'->>'geo_longitude','')::double precision
		    ) as geom_1b,
		    st_point(
		    	nullif(geo_bl->'result'->>'geo_latitude','')::double precision,
		    	nullif(geo_bl->'result'->>'geo_longitude','')::double precision
		    ) as geom_bl,
		    st_point(
				nullif(geo_bn->'result'->>'geo_latitude','')::double precision,
				nullif(geo_bn->'result'->>'geo_longitude','')::double precision
			) as geom_bn
		from facdb_base
	) a LEFT JOIN dcp_mappluto b ON b.bbl::bigint::text = a.geo_bbl
) a LEFT JOIN doitt_buildingcentroids b ON b.bin::bigint::text = a.geo_bin ) a
```

**Comment by AmandaDoyle** [comment]
AD's very simple notes about geocoding logic
Goal - map to most percise location and make sure all geospatial attributes are in sync
Heirarcy for getting the point:
1) map to BIN centroid
2) map to BBL centroid
3) map to centroid of source data (i.e. source point or centroid of source polygon)

Do we get point and do spatial joins to fill in spatial boundary data?

For discussion:
Scenarious listed in order of exploration.

Scenario 1 Good address in input data:
- 1B
- Get BIN
- Get BIN centroid from DOITT
- If not then take BBL centroid from PLUTO
Do we take the normalized address?

Scenario 2 Good BIN in input data:
- Get BIN centroid from DOITT

Scenario 3 Good BBL in input data :
- Get BBL from PLUTO
- Backfill BIN information.  Only backfill BIN if there is only one building on lot.

Scenario 4 spatial data in input data:
- Map XY or Lat/Long coordinates to point
- Take centroid of polygon data
- Backfill BBL and BIN information.  Only backfill BIN if there is only one building on lot.
