### ISSUE TITLE
Change parser prefixes to specify geo function

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-facilities#360]
For example. in functionBL.py:

```python
    def parser(self, geo):
        return dict(
            bl_bin=geo.get("Building Identification Number (BIN)", ""),
            bl_latitude=geo.get("Latitude", ""),
            bl_longitude=geo.get("Longitude", ""),
            bl_grc=geo.get("Geosupport Return Code (GRC)", ""),
            bl_reason_code=geo.get("Reason Code", ""),
            bl_message=geo.get("Message", "msg err"),
        )
```

This way we know where different fields originated if we nest geocoding functions.

**Comment by SPTKL** [comment]
this is not necessary, because the results will be stored in separate columns as json
geo_1b, geo_bl, geo_bn

we can to get 1b latitude, we would have to do 
`select geo_1b ->> results ->> latitude` there's no way we would miss the origin of the field

**Comment by mgraber** [comment]
> this is not necessary, because the results will be stored in separate columns as json
> geo_1b, geo_bl, geo_bn
> 
> we can to get 1b latitude, we would have to do
> `select geo_1b ->> results ->> latitude` there's no way we would miss the origin of the field

We should at least specify 1a versus 1e GRCs, errors, messages in the 1B call.

**Comment by SPTKL** [comment]
isn't that specified via GRC vs GRC2
