### ISSUE TITLE
facdb_agency - create agency lookup for oversight agency and operators

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#367]
Questions: 
1. NYPL public or non public?
https://github.com/NYCPlanning/db-facilities/blob/70286eeb2c9947127dd587dc20d5adeee354b662/facdb_build/sql/nypl_libraries.sql#L45-L49
> NYPL is public

2. NYS DOH opabbrev = 'Non-public' and optype='Public', this doesn't make sense
![image](https://user-images.githubusercontent.com/13207770/117821605-bf761900-b239-11eb-8cb4-2993f6108695.png)
https://github.com/NYCPlanning/db-facilities/blob/70286eeb2c9947127dd587dc20d5adeee354b662/facdb_build/sql/nysdoh_healthfacilities.sql#L62-L73
> NYS DOH opabbrev and optype should be 'Public'
3. Weird colp agencies that cannot be googled: NYCUDC, NYCCNTYC
> Looking into this

**Comment by SPTKL** [comment]
Current oversight agency and operator look up, there are inconsistencies
```sql
SELECT DISTINCT
	 overagency, overabbrev, overlevel, b.opabbrev, b.optype 
FROM facilities a JOIN (
	SELECT DISTINCT opabbrev, optype FROM facilities
) b ON a.overabbrev = b.opabbrev
```
