### ISSUE TITLE
CNTYC is short for County Clerk

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#444]
Update [agency lookup table](https://github.com/NYCPlanning/db-facilities/blob/develop/facdb/data/lookup_agency.csv) so that  CNTYC maps to County Clerk. 
Source: https://www1.nyc.gov/assets/planning/download/pdf/data-maps/open-data/colp_readme.pdf

**Comment by AmandaDoyle** [comment]
Change `NYCCNTYC` to `CNTYC` and `New York City County Clerk` to `County Clerk` in https://github.com/NYCPlanning/db-facilities/pull/447/files#diff-48d28faea7ef8b0b13820dfa1ad81a3d5ba7ec0d7eba7d12232dd66daf8d6aa6

**Comment by SPTKL** [comment]
fixed
