### ISSUE TITLE
Why are there fewer records from dca_operatingbusinesses?

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#452]
For dca_operatingbusinesses, we are only taking records that aren't yet expired, and in a subset of industries
```sql
select count(*) from dca_operatingbusinesses."2020/07/06" where license_expiration_date::Date >= '2020/07/06'
and industry in ( 'Scrap Metal Processor', 'Parking Lot', 'Garage', 'Garage and Parking Lot', 'Tow Truck Company')
```
Will get us 1844 records out of 203616 records
```sql
select count(*)
from dca_operatingbusinesses."2020/10/23" 
where license_expiration_date::Date >= '2020/10/23'
and industry in ( 'Scrap Metal Processor', 'Parking Lot', 'Garage', 'Garage and Parking Lot', 'Tow Truck Company')
```
Will get us 1961 records out of 266498 records
```sql
select count(*)
from dca_operatingbusinesses."2020/10/23" 
where license_expiration_date::Date >= '2021/04/02'
and industry in ( 'Scrap Metal Processor', 'Parking Lot', 'Garage', 'Garage and Parking Lot', 'Tow Truck Company')
```
Will get us 147 records out of 266498 records

---
using 2021/04/02 data
Will get us records 630 out of 268031 records using the same filter

## Conclusion: 
1. license application speed slowed down a lot (60k+ increase between July and October 2020, but only 2k+ increase between October 2020 and April 2021)
2. Licenses are expiring
3. So this overall leads to fewer dca_operatingbusinesses records

also based on Open data website
![image](https://user-images.githubusercontent.com/13207770/120508601-dc63bf00-c395-11eb-80a9-8b87414b22e7.png)
https://www1.nyc.gov/site/dca/businesses/licenses.page
we basically can no longer determine if licenses are expired using the dataset
https://www1.nyc.gov/assets/dca/downloads/pdf/businesses/Does-Your-Consumer-Affairs-License-Expire-February-through-June-2020.pdf

![image](https://user-images.githubusercontent.com/13207770/120509509-91967700-c396-11eb-82e1-f4779724f4b9.png)

---

**Comment by mgraber** [comment]
The number of records depends on the run date.
In the old workflow:
https://github.com/NYCPlanning/db-facilities/blob/70286eeb2c9947127dd587dc20d5adeee354b662/facdb_build/sql/dca_operatingbusinesses.sql#L71-L72

In the new workflow:
https://github.com/NYCPlanning/db-facilities/blob/2484da906740a81e1f9ea5dc9dca56117b9108bb/facdb/pipelines.py#L58-L66

**Comment by AmandaDoyle** [comment]
- Set `license_expiration_date` to today for scrap metal
- Set `license_expiration_date ` to March 12, 2020 for everything else that we get

**Comment by AmandaDoyle** [comment]
@SPTKL where does the date filtering happen for `dca_operatingbusinesses`?  I checked facdb and data library and can't find it.

**Comment by SPTKL** [comment]
> @SPTKL where does the date filtering happen for `dca_operatingbusinesses`? I checked facdb and data library and can't find it.

check molly's comment above ^
