### ISSUE TITLE
QAQC Report: Number of duplicate BINs by FacSubgroup

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#464]
Add QAQC report that reports the number of duplicate BINS by FacSubgroup

```
WITH dupbins as (
SELECT bin, facsubgrp, COUNT(*) as bincount
FROM facdb 
WHERE bin::text not like '%000000'
AND bin IS NOT NULL
GROUP BY bin, facsubgrp)
SELECT facsubgrp, COUNT(*)
FROM dupbins
WHERE bincount > 1
GROUP BY facsubgrp
ORDER BY count desc;
```

**Comment by SPTKL** [comment]
we can use filter to avoid necessary joins 
```sql
select 
	facsubgrp,
	count(*) as count_total,
	count(distinct bin) filter (where bin not like '%000000') as count_distinct_bin,
	count(*) filter (where bin like '%000000') as count_million_bin,
	count(*) filter (where bin is null) as count_null_bin,
	count(*) filter (where geom is null) as count_wo_geom
from facdb.facdb
group by facsubgrp
```

**Comment by AmandaDoyle** [comment]
@SPTKL this issue is good to go; we definitely want this reported out.

I see what your logic is doing but it's not easily telling me the subgroups that have lots of duplicate BINs

We can talk this through to find a happy medium if useful

**Comment by mgraber** [comment]
@AmandaDoyle @SPTKL 

I would suggest:
```sql
SELECT 
	facsubgrp,
	count(*) as count_total,
	count(distinct bin) as count_distinct_bin,
	count(*) - count(distinct bin) as count_repeat_bin,
	count(*) filter (where bin is null) as count_null_bin,
	count(*) filter (where geom is null) as count_wo_geom
FROM facdb
GROUP BY facsubgrp
ORDER BY count_repeat_bin DESC;
```
Where the field `count_repeat_bin` captures the number of records with BINs already captured by another record. I think this makes more sense than thinking of "duplicates." Although this depends on what we're trying to capture... Do we want to be counting the number of records having a repeated BIN, or the number of BINs where there are more than one record? For example, the term "duplicate" suggests pairs. But we might have 3 or 4 records containing the same BIN. If we count records with repeated BINs, we capture these repeats. If we only count BINs with more than one record, this will look the same as a BIN with only 2 records.

**Comment by AmandaDoyle** [comment]
Maybe something like this?
```
SELECT 
	facsubgrp,
	count(*) as count_total,
	count(distinct bin) as count_distinct_bin,
	count(*) - count(distinct bin) filter (where bin is not null and bin::text not like '%000000') as count_repeat_bin,
	count(*) filter (where bin is null) as count_null_bin,
	count(*) filter (where geom is null) as count_wo_geom
FROM facdb
GROUP BY facsubgrp
ORDER BY count_repeat_bin DESC;
```
Let's count the number of records with a repeated BIN, but we need to exclude million bins and NULL bins.  

So I make sure I'm interpreting this right, a value of 1120 in count_repeat_bin for MENTAL HEALTH would mean that there are 1120 records with a non distinct BIN for that sub group, excluding null and million bins.  Is that correct?

**Comment by mgraber** [comment]
@AmandaDoyle correct

**Comment by SPTKL** [comment]
Also there shouldn't be million bins. 
https://github.com/NYCPlanning/db-facilities/blob/c7b6132633773d19bdaaf35dca8d68332a193811/facdb/sql/_create_facdb_spatial.sql#L45

**Comment by AmandaDoyle** [comment]
I realized there was an error in my code. I think it should be
count(*) filter(where bin is not null) - count(distinct bin) as count_repeat_bin,
