### ISSUE TITLE
QAQC: When deduplicating between sources report what record was removed.

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#466]
When deduplicating between sources report what record was removed.

**Comment by SPTKL** [comment]
this should only apply to #468 #467 right?

**Comment by AmandaDoyle** [comment]
@SPTKL  Yes.  You said you had an idea on how to implement this, so if you make the change to the the nycha community center workflow, I'll follow the framework and build out these workflows

**Comment by SPTKL** [comment]
incorporated
