### ISSUE TITLE
Add fuzzy string matching for deduplication for of Day Care

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#467]
Day care names are a little messy.  Add fuzzy string matching to remove duplicates

Logic is:
- Same date source (this has no impact)
- Same BIN, but no million BINs
- Facsubgroup is DayCare
- Facname doesn't have a number
- Facname matches with 3 or less changes

When selecting the record to keep, decide which factype to keep (i.e. keep Day Care or School Based Child Care - Preschool)
> AD: I vote to keep the Day Care record instead of the School Based Child Care - Preschool record, because there are more Day Care records in FacDB

Logic for identifying records that are duplicates
```
SELECT
	a.bin,
	a.factype as factype_a,
	b.factype as factype_b,
	a.datasource as datasource_a,
	b.datasource as datasource_b,
	a.facname as facname_a,
	b.facname as facname_b
FROM facdb a
JOIN facdb b
ON a.uid > b.uid
AND a.datasource = b.datasource
AND a.bin::text not like '%000000'
AND a.bin = b.bin
AND a.facsubgrp = b.facsubgrp
AND a.facsubgrp = 'DAY CARE'
AND levenshtein(UPPER(regexp_replace(a.facname, '[^a-zA-Z0-9]+', '','g')),UPPER(regexp_replace(b.facname, '[^a-zA-Z0-9]+', '','g')))<=3
AND UPPER(regexp_replace(a.facname, '[^a-zA-Z0-9]+', '','g'))<>UPPER(regexp_replace(b.facname, '[^a-zA-Z0-9]+', '','g'))
AND a.facname ~ '^[^0-9]+$'
AND b.facname ~ '^[^0-9]+$';
```

**Comment by mgraber** [comment]
@AmandaDoyle Which record do we keep in cases of duplicates? Does it matter?

**Comment by SPTKL** [comment]
incorporated
