### ISSUE TITLE
Geocode COLP to get BIN?

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#474]
There are no BINs for COLP records.  Geocode COLP to get BIN value.

Question, do we then map to the BIN?  This contradicts issue #356

**Comment by SPTKL** [comment]
This can happen in the facdb_spatial.sql step:

```sql
UPDATE facdb_spatial
SET bin = colp_bins.bin
FROM (
	SELECT 
		_dcp_colp.uid,
		doitt_buildingfootprints.bin
	FROM _dcp_colp
	LEFT JOIN doitt_buildingfootprints
	ON ST_Intersects(_dcp_colp.wkb_geometry, ST_SetSRID(doitt_buildingfootprints.the_geom::geometry, 4326))
) colp_bins
WHERE facdb_spatial.uid = colp_bins.uid;
```

Also for some reason doitt_buildingfootprints wkb_geometry fields are all NULL, would need to investigate in data-library
This query is really slow because there's no spatial index

**Comment by mgraber** [comment]
Results from 1B (geo_bin) versus spatial join with doitt_buildingfootprints (fp_bin).

```sql
SELECT 
		_dcp_colp.uid,
		_dcp_colp.bin as geo_bin,
		doitt_buildingfootprints.bin as fp_bin
FROM _dcp_colp
LEFT JOIN doitt_buildingfootprints
ON ST_Intersects(_dcp_colp.wkb_geometry, ST_SetSRID(doitt_buildingfootprints.the_geom::geometry, 4326))
```

[colp_bins.csv](https://github.com/NYCPlanning/db-facilities/files/6618669/colp_bins.csv)

**Comment by SPTKL** [comment]
ahh, this is much easier!
