### ISSUE TITLE
Remove 3 addressnum values that are text (i.e. W, S, and PUMP-HO)

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#495]
Remove 3 addressnum values that are text (i.e. W, S, and PUMP-HO)

**Comment by AmandaDoyle** [comment]
@SPTKL  Flagging for your input

**Comment by mgraber** [comment]
@AmandaDoyle does this include cases where the addressnum contains W or S? For example, `461-W 131ST ST`, which currently has addressnum of `461W`.

**Comment by mgraber** [comment]
One possible solution is to ensure that addressnum contains at least one number:

```sql
SELECT * FROM facdb
WHERE addressnum !~ '[0-9]';
```

**Comment by AmandaDoyle** [comment]
@mgraber this does not include cases where the addressnum contains W or S and a digit.  This is only for records without a number in the addressnum field.  Right now, there are only three records, which are W, S, and PUMP-HO.  I think that this should take place at `_create_facdb_address` but would like @SPTKL input
