### ISSUE TITLE
Why does addressnum + street name not always equal address?

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#496]
![Screen Shot 2021-06-14 at 7 54 09 PM](https://user-images.githubusercontent.com/5611960/122310584-a159a380-cede-11eb-85c3-6910817ecfcc.png)

**Comment by AmandaDoyle** [comment]
@SPTKL  Flagging for your input

**Comment by mgraber** [comment]
We currently take full address field from source:
https://github.com/NYCPlanning/db-facilities/blob/497ebefb7846506da76e3e28281dc45c1a175ce8/facdb/sql/_create_facdb_address.sql#L7-L11

Should we instead change this to:
```sql
	UPPER(CASE
		WHEN source = 'dcp_colp' then address
		WHEN geo_grc in ('00', '01') and geo_grc2 in ('00', '01')
		THEN nullif(geo_house_number||' '||geo_street_name,'')
	ELSE geo_house_number||' '||geo_street_name END) as address
```

**Comment by AmandaDoyle** [comment]
@mgraber  Yes, confirmed with LS to change what you've outlined above, but question I have - should pipes (`||`) be changed to `CONCAT`?

**Comment by mgraber** [comment]
> @mgraber Yes, confirmed with LS to change what you've outlined above, but question I have - should pipes (`||`) be changed to `CONCAT`?

Yes, probably, if we want an address to contain a street name in cases where street name exists but house number is null.

**Comment by mgraber** [comment]
Based on #396:
- If source is colp:
    - Take addressnum as addressnum
    - Take streetname as streetname
    - Take address as address
- If source is not colp:
    - If geocoded, (grc and grc2 == '00' or '01'), take nullif(CONCAT(geo_house_number,' ',geo_street_name),' '), or nullif(geo_street_name, ' ') if geo_house_number is NULL for address
    - If not geocoded, (grc or grc2 <> '00' or '01'), set addressnum and streetname as NULL, and fill address with source address
