### ISSUE TITLE
Edits to exported files

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#520]
- [ ] Schema for shapefile and fgdb
The text fields in both the fgdb and the shapefile are not the same length as the previous version. In the fgdb, they are all 65,000+ characters. In the shapefile, they are larger than before, e.g., - [ Addressnum went from 12 to 80 characters. We need to keep the same schema (even if it means cutting off some characters). We should discuss this one.
- [ ] Shapefile is not projected to SPC
- [ ] Don't include unmapped items in either spatial dataset

**Comment by SPTKL** [comment]
for shapefile and fgdb, gis did post processing in previous releases
