### ISSUE TITLE
nysdec_lands http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1114

### ISSUE THREAD

**Issue by td928** [NYCPlanning/db-facilities#527]

**Comment by SashaWeinstein** [comment]
why was this issue opened?

**Comment by td928** [comment]
this might have been a little premature and also probably should be data library issue. The link in data library to update `nysdec_lands` no longer seems to work. See here https://gisservices.its.ny.gov/arcgis/rest/services/dec_lands/MapServer/0/query?where=1=1&outfields=*&f=geojson

**Comment by td928** [comment]
the link to description of the dataset is here: http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1114 found in the data library template

**Comment by SashaWeinstein** [comment]
I changed data library to take the shapefile from the ["zip"](http://gis.ny.gov/gisdata/data/ds_1114/DEC_lands.zip) link found in the top row of the table on the [website linked above](http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1114). The data from this dataset works with the existing pipeline and adds one new record. I had to change data library and made [a corresponding issue in that repo](https://github.com/NYCPlanning/db-data-library/issues/223)
