### ISSUE TITLE
Docker Compose Issue 

### ISSUE THREAD

**Issue by td928** [NYCPlanning/db-facilities#530]
When docker compose up `.devcontainer/docker-compse.yml`

Service 'facdb' failed to build : Build failed

E: Unable to locate package postgresql-client-11

**Comment by SashaWeinstein** [comment]
This was resolved by removing the "-11" right @td928?

**Comment by td928** [comment]
Yeah I created a branch with that change. Can turn it into a PR. @SashaWeinstein

**Comment by SashaWeinstein** [comment]
@td928 was this change merged in? believe it was but want to double check

**Comment by td928** [comment]
Yes I think a feature branch or PR did not end up created specifically for this. But checking both of docker files changes were merged in for the Q2 build branch

**Comment by SashaWeinstein** [comment]
ok great
