### ISSUE TITLE
Datasets.yml defaults to latest

### ISSUE THREAD

**Issue by mbh329** [NYCPlanning/db-facilities#546]
`datasets.yml` specifies which version of a dataset to use for a facilities run. In earlier iterations of the file, the dataset version is specified but @td928 @SashaWeinstein and @mbh329 thought it would be better to default to latest than to update the version everytime fac db is run with updated data from DO. However @AmandaDoyle made a good point that it is easier to debug the data updates if we keep the version specified

**Comment by AmandaDoyle** [comment]
Hi - I apologize for not commenting here.  I replied in the closed pull request.  See feedback

> I apologize for not weighing in on this sooner. Let's see how this works out. The reason why a specific version was set for each dataset was because of the lengthy QA and iteration process, so if a dataset was updated during a review process it could cause us to have to update the ingestion process and/or introduce new anomalies in a QAQC report, further slowing the review process.

**Comment by SashaWeinstein** [comment]
I was thinking about this last night and had a new idea on how to track the versioning on the facDB side. Currently we can point to a specific version or grab latest. What if when we grabbed latest, we wrote the version to datasets.yml under a new key (something like version_pulled). 
This makes it easy to track which versions have changed between runs, and easily find the last "working" version of a source dataset

**Comment by td928** [comment]
All behind Sasha's proposal. Only question remains for me what type of file we want to write out to? Would a yml file makes sense since we might reuse it for future rerun?

**Comment by SashaWeinstein** [comment]
Yea Te I think writing to a .yml file is a great idea. Does this .yml file have the same format as `datasets.yml`? The idea being that we could take the .yml produced by the last release, pop it into the `facdb` folder and re-create that exact same run?

**Comment by AmandaDoyle** [comment]
@SashaWeinstein and @td928 is this issue closed?

**Comment by td928** [comment]
yep #556 got to this and is merged in
