### ISSUE TITLE
Update doe_universalprek to Open Data

### ISSUE THREAD

**Issue by td928** [NYCPlanning/db-facilities#551]

**Comment by AmandaDoyle** [comment]
@td928 responding to your comment in issue #526 here
Before implementing any changes I suggest fully scoping out the following, which would have downstream changes
- changes to factypes, which would impact categorization
- if all records have a lat/long AND if the lat/longs fall inside the lot and not on the street centerline, we can use that for the geometry.  See the geocoding guidelines [here](https://github.com/NYCPlanning/db-facilities/wiki/Guidelines-for-bringing-in-dataset-into-FacDB#python).
Then let's briefly sync up to agree on changes before you implement anything.

**Comment by td928** [comment]
sounds good! So far I am testing out all changes on feature branchs and also not pushing to s3 as latest. I also think we might need to think it over because the update for the dataset last july is on meta data. The dataset itself has not been updated since 2017 according to the socrata pull. @AmandaDoyle

**Comment by AmandaDoyle** [comment]
Good catch.  Also, this jogged my memory.  See this issue for context #8 
We cannot use Open data
