### ISSUE TITLE
Update projection of shapefile to Long Island State Plane

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#559]
Update projection of shapefile to Long Island State Plane

I think that the change needs to be made [here](https://github.com/NYCPlanning/db-facilities/blob/develop/facdb/bash/config.sh).  See [old PR ](https://github.com/NYCPlanning/db-facilities/pull/506)

I do remember having issues implementing this in the past, so if this is a problem GIS can change the projection before publishing data on Bytes and Open Data.

**Comment by abrieff** [comment]
Addressed by #566
