### ISSUE TITLE
Update source data for doe_lcgms

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#560]
There are more up to date versions of doe_lcgms data in data library (see [here](https://cloud.digitalocean.com/spaces/edm-recipes?i=266877&path=datasets%2Fdoe_lcgms%2F))

Is there a reason we didn't update these data when we produced FacDB?  If so can we update the source data for LCGMS?

**Comment by td928** [comment]
@AmandaDoyle you are right. doe_lcgms was updated by me recently and it just looks like in the last build we forgot to remove the tag which is pointed to the earlier version.

**Comment by AmandaDoyle** [comment]
@td928 would you like take this on?  Confirm latest version has same schema, etc., then update to point to most recent version?

**Comment by td928** [comment]
yes I will work on this now.
