### ISSUE TITLE
Pop number needs to be renamed to uid

### ISSUE THREAD

**Issue by SashaWeinstein** [NYCPlanning/db-facilities#574]
`dcp_pops` should still have pop_numbers as uid, but the field name needs to be uid

**Comment by mbh329** [comment]
@SashaWeinstein @td928  I realize that neither have us have looked at db-fac but might be good to go over this in more detail?

**Comment by SashaWeinstein** [comment]
Unfortunately I don't remember the context here at all. We can go over it if it's important but I don't know how helpful I can be
