### ISSUE TITLE
Issues with NTA2020 & CT2020 values being NULL and wrong formatting

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities#577]
MC flagged that
1) Both the NTA2020 & CT2020 fields are mostly null – 26,733 of 32,437 records are null
Figure out why records are NULL and fix.
2) The length of all numeric fields in the facilities raw data is 65,536
Determine what the length of the numeric fields should be and set this in the schema.

**Comment by croswell81** [comment]
For bullet 2 - it was the Text fields that had a length of 65,536, not the numeric fields. The numeric fields in ESRI format do not allow us to set a length or precision (see image below).

The text field lengths for NTA and CTs should be the following:
NTA2010 - 4
NTA2020 - 6
CT2010 - 6
CT2020 - 6

![image](https://user-images.githubusercontent.com/33908810/181283102-511b7f31-5539-4cc8-9766-61606a74b312.png)
