### ISSUE TITLE
Update `foodbankny_foodbanks` description in issue template

### ISSUE THREAD

**Issue by mbh329** [NYCPlanning/db-facilities#586]
I found a new way to download the data from the google map so opening up an issue to update the description in the manual upload section for `foodbanksny_foodbank`

**Comment by fvankrieken** [comment]
This seems done as well, right?

**Comment by damonmcc** [comment]
[link to Manual Download section](https://nyco365.sharepoint.com/sites/NYCPLANNING/cp/_layouts/15/Doc.aspx?sourcedoc={8f26527c-f42c-46be-9e29-d73a7a80586a}&action=view&wd=target%28Untitled%20Section.one%7Ced58a6a1-1f68-43e6-8b83-42dda5a6e985%2FREAD%20ME%20for%20HED%7C3797d982-1fc6-4800-ad3c-d46e5c1e2a8f%2F%29&wdorigin=703) in issue template

It seemed updated but then I followed the instructions and don't see a download as CSV option:
<img width="653" alt="image" src="https://user-images.githubusercontent.com/7444289/227543399-8f6048a1-7b5c-4eb7-b3e4-23c44e627705.png">
